### ISSUE TITLE
AWS Setup [Back-end] (5/20)

### ISSUE THREAD

**Issue by SerenaJewels** [gotechnica/technica-site-2024#1]
This task involves setting up the backend components for registration on AWS. You guys will primarily be working on creating new DynamoDB tables and updating lambdas to store the altered fields from this year. While we aren't changing too much from last year, we will have a few changes such as the new track and a few new accommodations.

If you are new to AWS or using Serverless, I highly recommend watching the AWS and Serverless tutorials listed in the video tutorials section

Here’s a link to the doc of questions: https://docs.google.com/document/d/1kHo5whDDe94q4RFNFd3zABfzvi_dOdzktJvoAJN2wQ4/edit?usp=sharing

**To-Do**
These tasks should be done in the backend folder of the [portal repository](https://github.com/gotechnica/portal/tree/main/backend) using Serverless
- [x] Create new tracking, registration, and statistics DynamoDB table for all three stages (dev, stg, prd) - total of 9 tables
- [x] Update module.exports.register function to check if newly added/updated fields are missing (use the names given in the questions doc, the new ones should be in blue)
- [x] Update module.exports.register function to store newly added/updated fields to the registration table
- [x] Update the registration S3 bucket to "technica-2024-resume" instead of "technica-2023-resume"

These tasks should be done on the AWS console manually
- [x] Update environment variables in register, track, and update lambdas to newly created 2024 DynamoDB table names
- [x] Update lambda function names of register, track, and update to “2024” instead of “2023", and make sure that the change is also reflected in the API gateway endpoints that are using the lambdas.

As discussed in the meeting, this is a lot, so we'd like to have around 3 people working on it together. You guys can work on it together or split up the tasks how you'd like. After you've updated everything, you can make a test event in the register lambda with the fields in the registration document to see if it gets properly stored in the tables. If you have any questions, feel free to put them in the #tech channel. You guys got this and good luck!
