### ISSUE TITLE
Hero Image & About Technica [Front-end] (6/3)

### ISSUE THREAD

**Issue by Aurynium** [gotechnica/technica-site-2024#12]
This task involves implementing the hero graphic and “About” section for the main page on the themed site. The hero image is the first thing that a visitor to the site will see, and is a sort of visual introduction of Technica. The “About” section is the follow-up to this, and provides more information about Technica as a whole.

**Hero Image**
This section includes the background illustration, Technica logo, themed tagline, dates and important info, and “register” and “learn more” buttons.
Important dates and info will just be text that appears under the Technica logo, but may need to be resized/repositioned based on the user’s device.
The “register” button should redirect users to the Technica registration page (link TBD, but make it /register for now).
The “learn more” button will have an info section pop up underneath talking a little about the hackathon. We don't have the blurb right now, so we just need the functionality to work. When the button is clicked again, the blurb will disappear.

**About Technica**
This section includes the section header, text box, and video container.
The text box and video container should each take up half the screen, split vertically down the center. For mobile, the text box should be above the video container. The video container should have room for a stylized border.

**To-Do**
- [x] Background Illustration
- [x] Technica Logo
- [x] Tagline & Dates and Important Info
- [x] “Register” Button
- [x] “Learn More” Button
- [x] “About Technica” Section Header
- [x] Text Box
- [x] Video Container

FIGMA: https://www.figma.com/design/wYIf6kQ0r033Tgd9n7HJaO/2024-Themed-Site?node-id=220-4&t=0niFF46d03LTFLnM-0
