### ISSUE TITLE
Hear From Past Hackers! [Front-end] (6/3)

### ISSUE THREAD

**Issue by Aurynium** [gotechnica/technica-site-2024#14]
This task involves implementing a carousel that displays testimonials and projects from previous hackers at Technica, as well as a button that links to the Technica Devpost.
The carousel should allow a user to navigate forwards and backwards through the slides using side buttons, and should loop smoothly from the last slide back to the first (and vice versa).
Each slide of the carousel should have:
Testimonial text
Hacker info
Hacker photo
“Flip to project” button
Underneath the carousel, there should be center-aligned text, and a center-aligned button that links to the Technica Devpost (https://technica-2023.devpost.com/project-gallery).

**To-Do**
- [x] Section Header + Subheader
- [x] Carousel Functionality (navigation buttons, looping)
- [x] Sample Carousel Slide (Placeholder images are fine for this)
- [x] Devpost text and button

FIGMA: https://www.figma.com/design/wYIf6kQ0r033Tgd9n7HJaO/2024-Themed-Site?node-id=220-4&t=0niFF46d03LTFLnM-0
