### ISSUE TITLE
Updating Tracks [Front-end] (5/20)

### ISSUE THREAD

**Issue by SerenaJewels** [gotechnica/technica-site-2024#2]
This year, we're getting rid of the Exploratory track and adding the Hardware Track. This task involves adding the hardware track to the track recommender that we had from last year. For context, the available tracks are beginner, general, research, startup, and exploratory, and each registrant has to select which track they want to do on the registration form. We want to display a list of tracks that we recommend as text next to the question. Here’s the criteria for when each track should be recommended:

Beginner: Is first hackathon or years of experience selected is 0-2 and **hacker must be in-person**
Startup: If topics of interest selected includes startup and hacker **must be in-person**
Research: If topics of interest selected includes research and hacker is **not in middle school or high school**
General: If not recommended anything

The conditions in bold are absolute conditions, so if they don’t meet those criteria, then that given track should not be displayed at all (meaning the user cannot select the option)

The tracks above should already be implemented. Since the hardware track is still a pretty new concept, we don't know exactly what the criterion will be. I would talk to events to see if they have any input for what the requirements are, but for now, add a new interest for hardware and make the criteria be:

Hardware: If topics of interest selected includes hardware and hacker **must be in-person**

Since the method relies on data that is selected by the user, it should probably be a computed function that updates based on the data that the recommender relies on. Thus, each of these inputs should be in a reactive object that gets updated when the user selects something new in the given fields.

**To-Do**
- [x] The recommended tracks are updated live based on user input
- [x] Necessary inputs are stored as a reactive element and used in the recommendation function
- [x] The function is created in <script setup>

It might be helpful to first see how the recommendations that are already in place are done. If you have any questions, feel free to post it in the #tech channel. You got this and good luck!
