### ISSUE TITLE
Registration Updates [Front-End] (5/20)

### ISSUE THREAD

**Issue by SerenaJewels** [gotechnica/technica-site-2024#3]
This task just updates registration for this year. [This doc](https://docs.google.com/document/d/1kHo5whDDe94q4RFNFd3zABfzvi_dOdzktJvoAJN2wQ4/edit) contains all the questions and criterion we'd like to have this year. I've also listed them below. Most of these will already have been implemented, but there are a few changes we're going to have. 

**To-Do**
- [x] Change the dates to this year's dates
- [x] Add the extra accommodations necessary
- [x] Make sure all other criterion are there

NOTE: the name of each field is contained in angular brackets [] - it is important that these names match exactly for validation purposes

This section of the form should contain the following fields:
- [x] T-shirt Size [size]

- 3XS
- 2XS
- XS
- S
- M
- L
- XL
- 2XL
- 3XL
- [ ] How did you hear about us? [hear]
- [ ]  Do you have any dietary restrictions? (dropdown, reference MLH outline) [dietaryRestrictions]
- [ ]  What severe food allergies do you have (multi-select + other option w/ text field)? [foodAllergies]
- [ ]  Accommodations (multi-select) [accommodations]
- Laptop
- ASL Interpreter
- Guides
- Face Masks
- Ear Plugs
- [ ] Upload Resume (file upload, optional) [resume] - you DO NOT need to implement any backend functionality for this, just the button

- All questions are required except for Accommodations and Upload Resume. All required questions should have a * at the end of the label
- Use VeeValidate Form and Field components (documentation: https://vee-validate.logaretm.com/v4/guide/overview/)
- DO NOT implement any validation

Most of the code should already be implemented, so feel free to use the code as a basis of what you need to do. You got this and good luck!
